"""Anti-contamination egress guard for sandbox-verified tasks.

A published fix lives on the package index and the code host, so an agent with
open network egress can fetch the gold patch (and often the hidden test) for the
very repo it is being asked to fix. We saw this empirically: an agent blocked
from the web fell back to `git diff origin/main` (closed by the git-history
scrub in `build_environment_dockerfile`), and when that was closed it ran
`pip download <pkg>==<fixed>` and read the fix straight out of the wheel.

This module ships a per-task `environment/docker-compose.yaml` overlay that
Harbor merges into its compose chain. It blackholes the fix-bearing hosts
(PyPI + GitHub + their CDNs) by mapping them to 0.0.0.0, so `pip download`,
`git fetch github.com`, `curl raw.githubusercontent...` and WebFetch against
those hosts all fail, while general internet (the model API, the agent's own
installer, apt) stays reachable.

This is a *denylist*, which is the realistic control at the docker-compose
layer (`extra_hosts` can add host->ip pins but cannot default-deny). It closes
the obvious, observed leak paths and, crucially, keeps a hosted agent like
claude-code runnable (a full `allow_internet=false` block breaks the agent's
own install + API access). The stricter, more robust form is a default-deny
egress allowlist proxy (allow only the package manager + model API), or a
PyPI mirror frozen to the task's base date so even the index lacks the fix.
See docs/pipelines/README.md and plans/reward_hacking_writeups.md.
"""

from __future__ import annotations

# Hosts that serve the published fix / hidden tests for an open-source repo.
# Blackholed to 0.0.0.0 in the agent's container at run time.
FIX_SOURCE_HOSTS: tuple[str, ...] = (
    "pypi.org",
    "pypi.python.org",
    "files.pythonhosted.org",
    "github.com",
    "api.github.com",
    "raw.githubusercontent.com",
    "codeload.github.com",
    "objects.githubusercontent.com",
)


def git_history_scrub(base_commit: str) -> str:
    """Return Dockerfile RUN lines that strip the repo to `base_commit`.

    The working tree may be reset to the base commit, but `.git` still holds
    the *future*: `origin/main`, tags, the fix commit, and the hidden test. An
    agent can `git diff origin/main HEAD` or `git show origin/main:<testfile>`
    to read the answer with zero network. This is a documented, repeated
    incident on SWE-bench (`git log --all | grep`). We remove the remote,
    delete every ref that points past the base, expire the reflog, and gc so
    the future commits are pruned, while keeping `base_commit` itself reachable
    (the verifier resets test files via `git checkout <base_commit> -- ...`).

    Append these lines AFTER the `git reset --hard <base_commit>` line.
    """
    return (
        f"RUN git checkout -q -B base {base_commit} \\\n"
        f"    && git remote remove origin 2>/dev/null || true\n"
        f"RUN for ref in $(git branch --format='%(refname:short)' | grep -vx base); do "
        f'git branch -D "$ref" 2>/dev/null || true; done \\\n'
        f"    && git tag -l | xargs -r git tag -d >/dev/null 2>&1 || true \\\n"
        f"    && git for-each-ref --format='%(refname)' refs/remotes 2>/dev/null "
        f"| xargs -r -n1 git update-ref -d 2>/dev/null || true \\\n"
        f"    && git reflog expire --expire=now --all 2>/dev/null || true \\\n"
        f"    && git gc --prune=now 2>/dev/null || true\n"
    )


def egress_guard_compose(hosts: tuple[str, ...] = FIX_SOURCE_HOSTS) -> str:
    """Return `environment/docker-compose.yaml` content blackholing `hosts`.

    Harbor includes a task's `environment/docker-compose.yaml` in its compose
    `-f` chain, so the `extra_hosts` entries land on the agent's `main` service.

    **DEPRECATED for pr_to_env — see `egress_firewall_compose`**. The extra_hosts
    approach only blocks connections that resolve via /etc/hosts. Agents that
    use IP-hardcoded connections or DoH resolvers bypass it entirely. Confirmed
    real: Opus fetched fix files from raw.githubusercontent.com on diffusers-12982
    while this guard was in effect. Kept for pr_runtime (mining, less exposed)
    and backwards compatibility.
    """
    lines = [
        "# Auto-generated by Repo2RLEnv: anti-contamination egress guard v1 (extra_hosts).",
        "# Blackholes the hosts that serve this repo's published fix and hidden",
        "# tests, so an agent cannot fetch the answer (pip download / git fetch /",
        "# WebFetch against these fail). General internet stays up so the agent",
        "# can install itself and reach its model API. See pipelines/_env_guard.py.",
        "# NOTE: bypassable via IP-hardcoded connections or DoH — see egress_firewall_compose",
        "# for the network-level v2 guard used by pr_to_env.",
        "services:",
        "  main:",
        "    extra_hosts:",
    ]
    lines += [f'      - "{h}:0.0.0.0"' for h in hosts]
    return "\n".join(lines) + "\n"


# ----------------------------------------------------------------------------
# Egress guard v2 — network-level firewall (CAP_NET_ADMIN + iptables)
# ----------------------------------------------------------------------------
#
# Confirmed reward-hacking cases (HF_ML_Bench_v0, July 2026):
#   - diffusers-12982 / opus, reward=1.0 — used `urllib.request.urlopen` to
#     download fix files from raw.githubusercontent.com at commit 61f1756.
#   - transformers-35348 / codex, reward=1.0 — fetched the entire model directory
#     from raw.githubusercontent.com/huggingface/transformers/main/....
#
# The v1 guard writes /etc/hosts entries, which agents bypass by connecting to
# resolved IPs directly or via out-of-band DNS (DoH). The v2 guard applies an
# iptables OUTPUT DROP default policy INSIDE the container and installs an
# allow-list of resolved IPs for the exact hosts the agent legitimately needs
# (model API, agent installer). No host on FIX_SOURCE_HOSTS gets an allow-list
# entry — so `pip install <pkg>` and `curl raw.githubusercontent...` both fail
# at the packet layer, regardless of how they resolved DNS.
#
# Requires: CAP_NET_ADMIN on the container (compose adds `cap_add: [NET_ADMIN]`).
# Compatible with Docker Desktop on macOS via qemu-emulated linux/amd64 images.

# Hosts the agent legitimately needs (model API + installer sources).
# Everything else is dropped. Extend this list at the pipeline level if a
# specific agent needs another endpoint (e.g. Bedrock, GKE, GitHub Copilot).
DEFAULT_ALLOW_HOSTS: tuple[str, ...] = (
    # Anthropic (claude-code + Sonnet/Opus)
    "api.anthropic.com",
    "claude.ai",
    # OpenAI (codex + GPT-5.3-codex)
    "api.openai.com",
    "chatgpt.com",
    "auth.openai.com",
    # HuggingFace Router (openhands-sdk + Qwen)
    "router.huggingface.co",
    "huggingface.co",
    # Anthropic MCP + Claude Code telemetry
    "statsig.anthropic.com",
    "cursor.sh",
    # NPM (some agent installers)
    "registry.npmjs.org",
    "registry.yarnpkg.com",
    # Agent-adapter bootstrap: agents (claude-code, codex, openhands-sdk) run
    # `apt-get install curl bash nodejs npm` at container startup. Blocking
    # these breaks the whole eval track (NonZeroAgentExitCodeError, exit 100).
    # Repo/PR fix content is NOT hosted on these — no reward-hack leak vector.
    "deb.debian.org",
    "security.debian.org",
    "ports.ubuntu.com",
    "archive.ubuntu.com",
    "pypi.org",
    "files.pythonhosted.org",
    "nodejs.org",
    # github-releases.githubusercontent.com hosts agent binaries (codex, etc.)
    # via GitHub Releases, distinct from raw.githubusercontent.com (blocked).
    "github-releases.githubusercontent.com",
)


def egress_firewall_entrypoint(allow_hosts: tuple[str, ...] = DEFAULT_ALLOW_HOSTS) -> str:
    """Return the /entrypoint-egress.sh script content.

    The script runs at container start with root privileges + CAP_NET_ADMIN.
    It resolves each `allow_hosts` entry to its A records, adds explicit
    OUTPUT ACCEPT rules for those IPs on tcp/443 (HTTPS) + tcp/80 (HTTP),
    then sets the OUTPUT default policy to DROP. Loopback + established
    connections stay ACCEPT.

    After firewall setup the script `exec`s the container's real command
    (typically `sleep infinity`) so PID 1 remains long-lived.
    """
    hosts_expr = " ".join(shlex_q(h) for h in allow_hosts)
    return f"""#!/bin/sh
# Auto-generated by Repo2RLEnv (_env_guard.egress_firewall_entrypoint).
# Applies a default-deny egress firewall inside this container, then execs
# the real command. Requires CAP_NET_ADMIN (see docker-compose cap_add).

set -eu

# If iptables isn't available (missing binary or no CAP_NET_ADMIN), we WARN
# and continue — the extra_hosts fallback is still in effect. This means the
# guard degrades to v1 rather than failing closed, which is the pragmatic
# choice for macOS Docker Desktop where iptables in emulated containers can
# be finicky. Production runs should verify the firewall with the probe
# script under plans/scripts/audit_reward_hacks.sh.
if ! command -v iptables >/dev/null 2>&1; then
    echo "[egress-guard] WARNING: iptables not installed; falling back to /etc/hosts guard only" >&2
elif ! iptables -L -n >/dev/null 2>&1; then
    echo "[egress-guard] WARNING: iptables not usable (missing CAP_NET_ADMIN?); falling back to /etc/hosts guard only" >&2
else
    # Reset any prior rules from a previous run.
    iptables -F OUTPUT 2>/dev/null || true
    iptables -F INPUT 2>/dev/null || true

    # Loopback always allowed.
    iptables -A OUTPUT -o lo -j ACCEPT
    iptables -A INPUT -i lo -j ACCEPT
    # Return traffic for connections we initiate.
    iptables -A OUTPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    iptables -A INPUT -m state --state RELATED,ESTABLISHED -j ACCEPT
    # DNS to the container's resolver (usually 127.0.0.11 in Docker userland).
    iptables -A OUTPUT -p udp --dport 53 -j ACCEPT
    iptables -A OUTPUT -p tcp --dport 53 -j ACCEPT

    # Resolve each allow-host and allow tcp/80 + tcp/443 to its IPs.
    for host in {hosts_expr}; do
        # `getent ahosts` returns IPv4 + IPv6; we take IPv4 only.
        for ip in $(getent ahostsv4 "$host" 2>/dev/null | awk '{{print $1}}' | sort -u); do
            iptables -A OUTPUT -d "$ip" -p tcp --dport 443 -j ACCEPT
            iptables -A OUTPUT -d "$ip" -p tcp --dport 80  -j ACCEPT
        done
    done

    # Default-deny outbound. Also LOG rejected packets to help debug false
    # positives during the audit (log lines land in dmesg / journalctl on the
    # host; Docker Desktop surfaces them in the container's stderr with
    # `--log-driver=json-file`).
    iptables -A OUTPUT -j LOG --log-prefix "[egress-drop] " --log-level 4 -m limit --limit 5/min || true
    iptables -P OUTPUT DROP

    echo "[egress-guard] iptables OUTPUT policy: DROP; allow-list applied" >&2
fi

# exec into the real command (compose CMD).
exec "$@"
"""


def shlex_q(s: str) -> str:
    """Single-quote-escape for embedding into a shell script."""
    if not s:
        return "''"
    if all(c.isalnum() or c in "._-+/:" for c in s):
        return s
    return "'" + s.replace("'", "'\\''") + "'"


def egress_firewall_dockerfile_fragment() -> str:
    """Return a Dockerfile fragment that installs iptables + the entrypoint script.

    Append this to the env's Dockerfile AFTER the git-history scrub. The
    fragment does NOT set an ENTRYPOINT/CMD — the emitter decides those
    invariants (per M3 gate #7). The compose file must add
    `cap_add: [NET_ADMIN]` so the entrypoint script can call iptables.
    """
    script = egress_firewall_entrypoint()
    # Bake the script into the image at /entrypoint-egress.sh (root:root, 0755).
    # Use a heredoc so we don't need multi-line RUN chaining.
    return (
        "# Egress firewall v2 (network-level, replaces /etc/hosts extra_hosts guard).\n"
        "# Docker-compose must set `cap_add: [NET_ADMIN]` for iptables to take effect.\n"
        "RUN (command -v apt-get >/dev/null 2>&1 && apt-get update && apt-get install -y --no-install-recommends iptables && rm -rf /var/lib/apt/lists/*) \\\n"
        "    || (command -v apk >/dev/null 2>&1 && apk add --no-cache iptables) \\\n"
        "    || echo 'WARNING: no known package manager; iptables not installed' >&2\n"
        "COPY --chmod=0755 <<'EGRESS_EOF' /entrypoint-egress.sh\n"
        f"{script}"
        "EGRESS_EOF\n"
    )


def egress_firewall_compose(
    allow_hosts: tuple[str, ...] = DEFAULT_ALLOW_HOSTS,
) -> str:
    """Return `environment/docker-compose.yaml` for the v2 network-level guard.

    - Adds `cap_add: [NET_ADMIN]` so the entrypoint can install iptables rules.
    - Overrides entrypoint to `/entrypoint-egress.sh` (which execs the real CMD
      after applying the firewall).
    - Keeps `extra_hosts` v1 mappings as a defense-in-depth belt-and-braces
      for any process that respects /etc/hosts (belt), while iptables catches
      IP-hardcoded traffic (suspenders).
    """
    lines = [
        "# Auto-generated by Repo2RLEnv: anti-contamination egress guard v2 (network-level).",
        "# Blocks all outbound traffic at the packet layer except a small allow-list of",
        "# model-API + agent-installer hosts. See _env_guard.egress_firewall_entrypoint.",
        "services:",
        "  main:",
        "    # cap_add grants the container the ability to modify netfilter rules.",
        "    # Without it, iptables commands in the entrypoint fail silently and the",
        "    # container falls back to the /etc/hosts guard alone.",
        "    cap_add:",
        "      - NET_ADMIN",
        "    # The v2 entrypoint applies the firewall then execs `sleep infinity`",
        "    # (or whatever compose command is set). Bake it into the image at",
        "    # /entrypoint-egress.sh (see egress_firewall_dockerfile_fragment).",
        '    entrypoint: ["/entrypoint-egress.sh"]',
        '    command: ["sleep", "infinity"]',
        "    # Belt-and-braces v1 guard: extra_hosts blackhole still catches any",
        "    # DNS-resolving traffic to these hosts before the firewall sees it.",
        "    extra_hosts:",
    ]
    lines += [f'      - "{h}:0.0.0.0"' for h in FIX_SOURCE_HOSTS]
    return "\n".join(lines) + "\n"

